# Generated by Django 5.0.4 on 2024-05-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=400, verbose_name='Ombor nomini kiritilsin ...')),
                ('action_type', models.CharField(choices=[('Kiritish', 'Kiritish'), ('Chiqarish', 'Chiqarish')], default='Kiritish', max_length=20)),
                ('storage_type', models.CharField(choices=[('Naqtga', 'Naqtga'), ('Qarzga', 'Qarzga')], default='Naqtga', max_length=20)),
                ('storage_date', models.DateTimeField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField(default=0)),
                ('size_type', models.CharField(choices=[("O'lchovli", "O'lchovli"), ("O'lchovsiz", "O'lchovsiz"), ('Formatli', 'Formatli')], default="O'lchovsiz", max_length=20)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('size', models.FloatField(default=1)),
                ('height', models.FloatField(default=1)),
                ('width', models.FloatField(default=1)),
                ('count', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField(default=0)),
                ('supplier_type', models.CharField(choices=[('Tezkor', 'Tezkor'), ('Doimiy', 'Doimiy')], default='Tezkor', max_length=20)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('added', models.DateTimeField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('storage_type', models.CharField(choices=[('Sanaladigan', 'Sanaladigan'), ('Sanalmaydigan', 'Sanalmaydigan')], max_length=20)),
                ('format', models.CharField(choices=[('Dona', 'Dona'), ('Metr', 'Metr'), ('Litr', 'Litr'), ('mL', 'mL'), ('Gramm', 'Gramm'), ('Mm', 'Mm'), ('Sm', 'Sm'), ('Km', 'Km'), ('Fut', 'Fut'), ('Metr kub', 'Metr kub')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('bar_code', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
