# Generated by Django 5.0.4 on 2024-04-03 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Kiritish', 'Kiritish'), ('Chiqarish', 'Chiqarish')], default='Kiritish', max_length=20)),
                ('storage_type', models.CharField(choices=[('Naqtga', 'Naqtga'), ('Qarzga', 'Qarzga')], default='Naqtga', max_length=20)),
                ('storage_date', models.DateTimeField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(choices=[("O'lchovli", "O'lchovli"), ("O'lchovsiz", "O'lchovsiz"), ('Formatli', 'Formatli')], default="O'lchovsiz", max_length=20)),
                ('storage_count', models.FloatField()),
                ('price', models.PositiveIntegerField()),
                ('size', models.FloatField(default=1)),
                ('height', models.FloatField(default=1)),
                ('width', models.FloatField(default=1)),
                ('quantity', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_type', models.CharField(choices=[('Tezkor', 'Tezkor'), ('Doimiy', 'Doimiy')], default='Tezkor', max_length=20)),
                ('name', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=11)),
                ('added', models.DateTimeField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('storage_type', models.CharField(choices=[('Sanaladigan', 'Sanaladigan'), ('Sanalmaydigan', 'Sanalmaydigan')], max_length=20)),
                ('measure', models.FloatField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('bar_code', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.format')),
            ],
        ),
    ]
