# Generated by Django 5.0 on 2024-03-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageproduct',
            name='height',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='storageproduct',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='storageproduct',
            name='size',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='storageproduct',
            name='size_type',
            field=models.CharField(choices=[("O'lchovli", "O'lchovli"), ("O'lchovsiz", "O'lchovsiz"), ('Formatli', 'Formatli')], default="O'lchovsiz", max_length=20),
        ),
        migrations.AddField(
            model_name='storageproduct',
            name='width',
            field=models.FloatField(default=1),
        ),
    ]
