# Generated by Django 5.0.4 on 2024-04-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_storageproduct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageproduct',
            old_name='quantity',
            new_name='count',
        ),
    ]
