# Generated by Django 5.0.4 on 2024-04-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_quantity_storageproduct_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageproduct',
            name='storage_count',
        ),
    ]
