# Generated by Django 5.0.4 on 2024-04-05 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_storageproduct_storage_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='products.supplier'),
        ),
    ]
