# Generated by Django 5.0 on 2024-03-29 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('Tezkor', 'Tezkor'), ('Doimiy', 'Doimiy')], default='Tezkor', max_length=20)),
                ('name', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=13)),
                ('added', models.DateTimeField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TradeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('Naqtga', 'Naqtga'), ('Qarzga', 'Qarzga')], default='Naqtga', max_length=20)),
                ('size_type', models.CharField(choices=[("O'lchovli", "O'lchovli"), ("O'lchovsiz", "O'lchovsiz"), ('Formatli', 'Formatli')], default="O'lchovsiz", max_length=20)),
                ('discount_price', models.PositiveIntegerField(default=1)),
                ('size', models.FloatField(default=1)),
                ('height', models.FloatField(default=1)),
                ('width', models.FloatField(default=1)),
                ('quantity', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Addition_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_price', models.PositiveBigIntegerField()),
                ('service_date', models.DateTimeField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addition_service', to='trade.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('Naqtga', 'Naqtga'), ('Qarzga', 'Qarzga')], default='Naqtga', max_length=20)),
                ('discount_type', models.CharField(choices=[("Narx bo'yicha chegirma", "Narx bo'yicha chegirma"), ('Umumiy savdodan chegirma', 'Umumiy savdodan chegirma')], default='Umumiy savdodan chegirma', max_length=24, null=True)),
                ('trade_date', models.DateTimeField()),
                ('check_id', models.IntegerField(blank=True, default=10000, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.client')),
            ],
        ),
    ]
