# Generated by Django 5.0 on 2024-03-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradedetail',
            name='category',
        ),
    ]
