# Generated by Django 5.0.4 on 2024-04-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedetail',
            name='detail_type',
            field=models.CharField(choices=[('Narxida', 'Narxida'), ('Chegirmada', 'Chegirmada')], default='Narxida', max_length=30),
        ),
    ]
