# Generated by Django 5.0 on 2024-04-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_remove_tradedetail_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradedetail',
            name='trade_type',
        ),
    ]
