# Generated by Django 5.0 on 2024-04-03 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_remove_tradedetail_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='discount_summa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tradedetail',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_details', to='trade.trade'),
        ),
    ]
