# Generated by Django 5.0 on 2024-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('cash', models.PositiveIntegerField(default=0)),
                ('card', models.PositiveIntegerField(default=0)),
                ('other_pay', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.PositiveIntegerField(default=0)),
                ('card', models.PositiveIntegerField(default=0)),
                ('other_pay', models.PositiveIntegerField(default=0)),
                ('dedline', models.DateTimeField()),
                ('added', models.DateTimeField()),
                ('check_id', models.IntegerField(blank=True, default=10000, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('action_type', models.CharField(choices=[('kirim', 'kirim'), ('chiqim', 'chiqim')], default='kirim', max_length=100)),
                ('transaction_type', models.CharField(choices=[('mijoz', 'mijoz'), ('ombor', 'ombor'), ('hodim', 'hodim'), ('boshqa', 'Boshqa')], max_length=100)),
            ],
        ),
    ]
