# Generated by Django 5.0 on 2024-03-29 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('products', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeoutcome',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.client'),
        ),
        migrations.AddField(
            model_name='financeoutcome',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.storage'),
        ),
    ]
