# Generated by Django 5.0 on 2024-04-02 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_initial'),
        ('trade', '0004_remove_tradedetail_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.client'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.trade'),
        ),
    ]
