# Generated by Django 5.0 on 2024-04-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[("Savdoga to'lov", "Savdoga to'lov"), ("Mijozga to'lov", "Mijozga to'lov")], default="Savdoga to'lov", max_length=100),
        ),
    ]
