# Generated by Django 5.0 on 2024-04-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_payments_client_alter_payments_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='dedline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
