# Generated by Django 5.0.4 on 2024-05-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
