# Generated by Django 5.0.4 on 2024-05-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
